In [15]:
import pandas as pd

file = r"C:\Users\admin\Desktop\Payroll Project\Payroll_Analytics_Dataset.xlsx"

employee = pd.read_excel(file, sheet_name="Employee")
payroll = pd.read_excel(file, sheet_name="Payroll")
expense = pd.read_excel(file, sheet_name="Expense")
travel = pd.read_excel(file, sheet_name="TravelExpense")

#Exploring data
employee.head()

,EmployeeID,EmployeeName,Department,Designation,Location,JoiningDate,Status
0,E00001,Karen Hernandez,Operations,Manager,Austin,2018-07-22,Active
1,E00002,William Jones,HR,Associate,Atlanta,2019-06-07,Active
2,E00003,James Jones,IT,Senior Associate,Atlanta,2025-12-16,Active
3,E00004,Mary Hernandez,IT,Manager,Chicago,2025-08-25,Active
4,E00005,Robert Rodriguez,Sales,Executive,Chicago,2025-09-10,Active

In [16]:
employee.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 7 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   EmployeeID    10000 non-null  object
 1   EmployeeName  10000 non-null  object
 2   Department    10000 non-null  object
 3   Designation   10000 non-null  object
 4   Location      10000 non-null  object
 5   JoiningDate   10000 non-null  datetime64[ns]
 6   Status        10000 non-null  object
dtypes: datetime64[ns](1), object(6)
memory usage: 547.0+ KB

In [17]:
employee.describe()

                      JoiningDate
count                       10000
mean   2022-02-01 15:16:42.240000
min           2018-01-01 00:00:00
25%           2020-01-15 00:00:00
50%           2022-01-30 00:00:00
75%           2024-02-21 06:00:00
max           2026-03-20 00:00:00

In [8]:
employee.shape

(10000, 7)

In [9]:
employee.columns

Index(['EmployeeID', 'EmployeeName', 'Department', 'Designation', 'Location',
       'JoiningDate', 'Status'],
      dtype='object')

In [18]:
payroll.head()

  PayrollID EmployeeID    Month  GrossSalary  Deductions  NetPay
0   P000001     E02743  2026-02       115481        3409  112072
1   P000002     E02945  2025-03        71015        2176   68839
2   P000003     E01466  2026-05        97534        8198   89336
3   P000004     E07702  2025-01       134208       13550  120658
4   P000005     E03957  2025-01       127994       14720  113274

In [19]:
payroll.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50000 entries, 0 to 49999
Data columns (total 6 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PayrollID    50000 non-null  object
 1   EmployeeID   50000 non-null  object
 2   Month        50000 non-null  object
 3   GrossSalary  50000 non-null  int64
 4   Deductions   50000 non-null  int64
 5   NetPay       50000 non-null  int64
dtypes: int64(3), object(3)
memory usage: 2.3+ MB

In [20]:
payroll.describe()

         GrossSalary    Deductions        NetPay
count   50000.000000  50000.000000   50000.00000
mean    92415.062520   8478.943060   83936.11946
std     27560.710789   3743.714747   27815.98234
min     45002.000000   2000.000000   30121.00000
25%     68416.000000   5244.000000   60016.75000
50%     92449.500000   8464.000000   84027.50000
75%    116365.250000  11715.000000  107741.75000
max    139999.000000  15000.000000  137891.00000

In [22]:
payroll.shape

(50000, 6)

In [23]:
payroll.columns

Index(['PayrollID', 'EmployeeID', 'Month', 'GrossSalary', 'Deductions',
       'NetPay'],
      dtype='object')

In [24]:
expense.head()

   ClaimID EmployeeID  ClaimDate ClaimType   Amount    Status
0  C000001     E01473 2025-03-21  Internet  2181.47  Approved
1  C000002     E02287 2025-05-04      Food   371.82   Pending
2  C000003     E08087 2026-04-24    Mobile  2089.91   Pending
3  C000004     E00889 2026-01-13   Medical  1288.83  Approved
4  C000005     E04421 2025-03-21  Internet  2356.87  Approved

In [25]:
expense.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50000 entries, 0 to 49999
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   ClaimID     50000 non-null  object
 1   EmployeeID  50000 non-null  object
 2   ClaimDate   50000 non-null  datetime64[ns]
 3   ClaimType   50000 non-null  object
 4   Amount      50000 non-null  float64
 5   Status      50000 non-null  object
dtypes: datetime64[ns](1), float64(1), object(4)
memory usage: 2.3+ MB

In [26]:
expense.shape

(50000, 6)

In [27]:
expense.columns

Index(['ClaimID', 'EmployeeID', 'ClaimDate', 'ClaimType', 'Amount', 'Status'], dtype='object')

In [28]:
#checking for nulls
employee.isnull().sum()

EmployeeID      0
EmployeeName    0
Department      0
Designation     0
Location        0
JoiningDate     0
Status          0
dtype: int64

In [30]:
#checking for duplicates
employee.duplicated().sum()

np.int64(0)

In [31]:
payroll.isnull().sum()

PayrollID      0
EmployeeID     0
Month          0
GrossSalary    0
Deductions     0
NetPay         0
dtype: int64

In [32]:
payroll.duplicated().sum()

np.int64(0)

In [33]:
expense.isnull().sum()

ClaimID       0
EmployeeID    0
ClaimDate     0
ClaimType     0
Amount        0
Status        0
dtype: int64

In [35]:
expense.duplicated().sum()

np.int64(0)

In [36]:
travel.isnull().sum()

TravelID      0
EmployeeID    0
TravelDate    0
FromCity      0
ToCity        0
Mode          0
Cost          0
dtype: int64

In [37]:
travel.duplicated().sum()

np.int64(0)

In [46]:
#Employee count by location
employee['Location'].value_counts().sort_values(ascending=False)

Location
Chicago    1293
Seattle    1290
Miami      1271
Dallas     1270
Atlanta    1261
Austin     1236
Phoenix    1214
Denver     1165
Name: count, dtype: int64

In [47]:
#Employee count by Department
employee['Department'].value_counts().sort_values(ascending=False)

Department
Sales         1308
Payroll       1288
Compliance    1257
IT            1246
Finance       1241
Operations    1239
HR            1211
Legal         1210
Name: count, dtype: int64

In [48]:
#Employee Status
employee['Status'].value_counts()

Status
Active      8960
Inactive    1040
Name: count, dtype: int64

In [57]:
#Employees joining by year
employee['Year'] = employee['JoiningDate'].dt.year
employee.groupby('Year')['EmployeeID'].count()

Year
2018    1248
2019    1206
2020    1221
2021    1216
2022    1267
2023    1170
2024    1204
2025    1183
2026     285
Name: EmployeeID, dtype: int64

In [59]:
#Employees by Department
employee.groupby('Department')['EmployeeID'].count().sort_values(ascending=False)

Department
Sales         1308
Payroll       1288
Compliance    1257
IT            1246
Finance       1241
Operations    1239
HR            1211
Legal         1210
Name: EmployeeID, dtype: int64

In [65]:
#Creating new column Deduction Percentage
payroll['Deduction Percentage'] = (payroll['Deductions']/payroll['GrossSalary']*100)
payroll['Deduction Percentage'].head()

0     2.952001
1     3.064141
2     8.405274
3    10.096268
4    11.500539
Name: Deduction Percentage, dtype: float64

In [68]:
#Creating new column Salary Band
def salary_band(net_pay):
    if net_pay < 60000:
        return "Low"
    elif net_pay <= 100000:
        return "Medium"
    else:
        return "High"

payroll['Salary Band'] = payroll['NetPay'].apply(salary_band)
payroll['Salary Band'].value_counts().sort_values(ascending=False)

Salary Band
Medium    20920
High      16588
Low       12492
Name: count, dtype: int64

In [72]:
#Claim by months
expense['Claim Month'] = expense['ClaimDate'].dt.month
expense['Claim Month'].value_counts().sort_values(ascending=False)

Claim Month
1     5694
5     5689
3     5655
4     5535
2     5170
6     4986
12    2981
8     2906
10    2875
7     2870
9     2841
11    2798
Name: count, dtype: int64

In [74]:
#Expense by Claim Type
expense.groupby('ClaimType')['Amount'].sum().sort_values(ascending=False)

ClaimType
Travel      10708837.07
Mobile      10674442.23
Hotel       10589972.18
Internet    10476015.53
Food        10461758.78
Medical     10303614.98
Name: Amount, dtype: float64

In [75]:
#Expense status overview
expense['Status'].value_counts()

Status
Approved    29780
Pending     10126
Rejected    10094
Name: count, dtype: int64

In [76]:
#Monthly expense
expense.groupby('Claim Month')['Amount'].sum()

Claim Month
1     7186345.71
2     6476546.34
3     7111404.19
4     6980274.04
5     7184440.17
6     6334133.83
7     3676179.20
8     3687628.59
9     3592002.04
10    3623113.27
11    3556129.68
12    3806443.71
Name: Amount, dtype: float64

In [78]:
#Months with highest expense
expense.groupby('Claim Month')['Amount'].sum().sort_values(ascending=False).head(5)

Claim Month
1    7186345.71
5    7184440.17
3    7111404.19
4    6980274.04
2    6476546.34
Name: Amount, dtype: float64

In [80]:
#Travel by mode
travel['Mode'].value_counts()

Mode
Train     16690
Cab       16680
Flight    16630
Name: count, dtype: int64

In [82]:
#Travel expense by mode
travel.groupby('Mode')['Cost'].sum()

Mode
Cab       15501032.21
Flight    15369951.76
Train     15381553.22
Name: Cost, dtype: float64

In [84]:
#Top 5 cities most travelled to
travel['ToCity'].value_counts().sort_values(ascending=False).head(5)

ToCity
Austin      4626
Atlanta     4608
Chicago     4594
Denver      4577
New York    4565
Name: count, dtype: int64

In [85]:
#Monthly travel trend
travel['TravelMonth'] = travel['TravelDate'].dt.month
travel.groupby('TravelMonth')['Cost'].sum()

TravelMonth
1     5238688.07
2     4891090.45
3     5343381.46
4     4994333.17
5     5283504.94
6     4763812.37
7     2698444.61
8     2666212.15
9     2503131.32
10    2732516.80
11    2556698.74
12    2580723.11
Name: Cost, dtype: float64

In [88]:
#Highest payroll depts

merged = pd.merge(employee, payroll, on='EmployeeID')
merged.groupby('Department')['NetPay'].sum().sort_values(ascending=False).head(5)

Department
Sales         551852574
Payroll       545403114
Compliance    528141472
IT            527357683
Finance       522609411
Name: NetPay, dtype: int64

In [90]:
employee.to_excel("employees_cleaned.xlsx", index=False)

payroll.to_excel("payroll_cleaned.xlsx", index=False)

expense.to_excel("expense_cleaned.xlsx", index=False)

travel.to_excel("travel_cleaned.xlsx", index=False)